In [5]:
import pandas as pd
df = pd.read_csv("../data/metadata_practice.csv")
df.head()

  patient condition  age  expression
0    P001    Normal   42         5.2
1    P002    Normal   51         6.1
2    P003   Adenoma   55        10.8
3    P004   Adenoma   61        12.3
4    P005       CRC   65        21.4

In [6]:
df.shape

(8, 4)

In [7]:
df.columns

Index(['patient', 'condition', 'age', 'expression'], dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient     8 non-null      str
 1   condition   8 non-null      str
 2   age         8 non-null      int64
 3   expression  8 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 388.0 bytes

In [9]:
df.describe()

             age  expression
count   8.000000     8.00000
mean   56.375000    14.92500
std     9.070163     8.46113
min    42.000000     5.20000
25%    50.500000     9.62500
50%    56.500000    11.95000
75%    62.000000    22.10000
max    70.000000    27.80000

In [10]:
df.sort_values("age")

  patient condition  age  expression
0    P001    Normal   42         5.2
6    P007   Adenoma   49        11.6
1    P002    Normal   51         6.1
2    P003   Adenoma   55        10.8
7    P008       CRC   58        24.2
3    P004   Adenoma   61        12.3
4    P005       CRC   65        21.4
5    P006       CRC   70        27.8

In [11]:
df.sort_values("age", ascending = False)

  patient condition  age  expression
5    P006       CRC   70        27.8
4    P005       CRC   65        21.4
3    P004   Adenoma   61        12.3
7    P008       CRC   58        24.2
2    P003   Adenoma   55        10.8
1    P002    Normal   51         6.1
6    P007   Adenoma   49        11.6
0    P001    Normal   42         5.2

In [12]:
df.sort_values("expression", ascending = False)

  patient condition  age  expression
5    P006       CRC   70        27.8
7    P008       CRC   58        24.2
4    P005       CRC   65        21.4
3    P004   Adenoma   61        12.3
6    P007   Adenoma   49        11.6
2    P003   Adenoma   55        10.8
1    P002    Normal   51         6.1
0    P001    Normal   42         5.2

In [14]:
crc_df = df[df["condition"] == "CRC"]

crc_df.head()

  patient condition  age  expression
4    P005       CRC   65        21.4
5    P006       CRC   70        27.8
7    P008       CRC   58        24.2

In [15]:
old_df = df[df["age"] >= 60]
print(old_df)

  patient condition  age  expression
3    P004   Adenoma   61        12.3
4    P005       CRC   65        21.4
5    P006       CRC   70        27.8

In [17]:
highexp_df = df[df["expression"] > 20]
print(highexp_df)

  patient condition  age  expression
4    P005       CRC   65        21.4
5    P006       CRC   70        27.8
7    P008       CRC   58        24.2

In [18]:
age_group = []

for age in df["age"]:
    if age >= 60:
        age_group.append("60_or_above")
    else:
        age_group.append("under_60")

df["age_group"] = age_group

df.head()

  patient condition  age  expression    age_group
0    P001    Normal   42         5.2     under_60
1    P002    Normal   51         6.1     under_60
2    P003   Adenoma   55        10.8     under_60
3    P004   Adenoma   61        12.3  60_or_above
4    P005       CRC   65        21.4  60_or_above

In [22]:
x = []
x.append("CRC")
df["x"] = x * len(df)

df.head()

  patient condition  age  expression    age_group    x
0    P001    Normal   42         5.2     under_60  CRC
1    P002    Normal   51         6.1     under_60  CRC
2    P003   Adenoma   55        10.8     under_60  CRC
3    P004   Adenoma   61        12.3  60_or_above  CRC
4    P005       CRC   65        21.4  60_or_above  CRC

In [24]:
import pandas as pd

df = pd.read_csv("../data/metadata_practice.csv")

df.shape

(8, 4)

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient     8 non-null      str
 1   condition   8 non-null      str
 2   age         8 non-null      int64
 3   expression  8 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 388.0 bytes

In [26]:
df.describe()

             age  expression
count   8.000000     8.00000
mean   56.375000    14.92500
std     9.070163     8.46113
min    42.000000     5.20000
25%    50.500000     9.62500
50%    56.500000    11.95000
75%    62.000000    22.10000
max    70.000000    27.80000

In [28]:
crc_df = df[df["condition"] == "CRC"]
print(crc_df)

  patient condition  age  expression
4    P005       CRC   65        21.4
5    P006       CRC   70        27.8
7    P008       CRC   58        24.2

In [29]:
old_df = df[df["age"] >= 60]
print(old_df)

  patient condition  age  expression
3    P004   Adenoma   61        12.3
4    P005       CRC   65        21.4
5    P006       CRC   70        27.8

In [31]:
df.sort_values("expression", ascending = False)

  patient condition  age  expression
5    P006       CRC   70        27.8
7    P008       CRC   58        24.2
4    P005       CRC   65        21.4
3    P004   Adenoma   61        12.3
6    P007   Adenoma   49        11.6
2    P003   Adenoma   55        10.8
1    P002    Normal   51         6.1
0    P001    Normal   42         5.2